import { Download, Filter, Search } from 'lucide-react'
import { useEffect, useState } from 'react'
import ThreatTable from '../components/ThreatTable'
import { API_BASE, api } from '../lib/api'

export default function ThreatExplorer({refresh}){const[rows,setRows]=useState([]);const[meta,setMeta]=useState({});const[filters,setFilters]=useState({attack_type:'',src_ip:'',dst_ip:'',host:'',severity:'',attack_status:'',min_confidence:''});const[loading,setLoading]=useState(true)
  async function load(){setLoading(true);const params=Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==''));try{const r=await api.get('/api/attacks',{params});setRows(r.data.items);setMeta(r.data)}finally{setLoading(false)}}
  useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[filters,refresh])
  const set=(name,value)=>setFilters(f=>({...f,[name]:value}));const exportQuery=new URLSearchParams(Object.entries(filters).filter(([,value])=>value!=='')).toString();return <div className="space-y-5"><section className="panel rounded-xl p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><div className="eyebrow">Threat records</div><h2 className="mt-1 text-xl font-black text-white">Investigate suspicious requests</h2><p className="mt-1 text-xs text-slate-500">{meta.total||0} alerts match this view</p></div><div className="flex gap-2"><a href={`${API_BASE}/api/export/csv${exportQuery?`?${exportQuery}`:''}`} className="btn-secondary flex items-center gap-2 text-xs"><Download size={15}/>Export CSV</a><a href={`${API_BASE}/api/export/json${exportQuery?`?${exportQuery}`:''}`} className="btn-secondary flex items-center gap-2 text-xs"><Download size={15}/>Export JSON</a></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-7"><input className="field" value={filters.src_ip} onChange={e=>set('src_ip',e.target.value)} placeholder="Source IP or CIDR"/><input className="field" value={filters.dst_ip} onChange={e=>set('dst_ip',e.target.value)} placeholder="Destination IP or CIDR"/><input className="field" value={filters.host} onChange={e=>set('host',e.target.value)} placeholder="Host contains"/><select className="field" value={filters.attack_type} onChange={e=>set('attack_type',e.target.value)}><option value="">All attack types</option>{['SQL_INJECTION','XSS','DIRECTORY_TRAVERSAL','COMMAND_INJECTION','SSRF','LFI','RFI','HTTP_PARAMETER_POLLUTION','TYPOSQUATTING','XXE_INDICATOR','WEB_SHELL_UPLOAD','BRUTE_FORCE'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select><select className="field" value={filters.severity} onChange={e=>set('severity',e.target.value)}><option value="">All severities</option>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select><select className="field" value={filters.attack_status} onChange={e=>set('attack_status',e.target.value)}><option value="">All statuses</option><option value="ATTEMPT">Attack Attempt</option><option value="PROBABLE_SUCCESS">Probable Success</option><option value="CONFIRMED_SUCCESS">Confirmed Success</option></select><input className="field" type="number" min="0" max="100" value={filters.min_confidence} onChange={e=>set('min_confidence',e.target.value)} placeholder="Min. confidence %"/></div></section><section className="panel overflow-hidden rounded-xl">{loading?<div className="p-16 text-center text-sm text-cyan-300">Querying local telemetry…</div>:<ThreatTable rows={rows}/>}</section></div>}
