"""Initial ByteForce schema for clean PostgreSQL deployments."""
from alembic import op
import sqlalchemy as sa
revision = "001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    op.create_table("network_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("timestamp", sa.DateTime()), sa.Column("src_ip", sa.String(64)), sa.Column("src_port", sa.Integer()), sa.Column("dst_ip", sa.String(64)), sa.Column("dst_port", sa.Integer()), sa.Column("protocol", sa.String(16)), sa.Column("method", sa.String(16)), sa.Column("host", sa.String(255)), sa.Column("uri", sa.Text()), sa.Column("normalized_url", sa.Text()), sa.Column("status_code", sa.Integer()), sa.Column("response_size", sa.Integer()), sa.Column("user_agent", sa.Text()), sa.Column("request_count", sa.Integer()))
    for column in ("timestamp", "src_ip", "dst_ip", "host"): op.create_index(f"ix_network_events_{column}", "network_events", [column])
    op.create_table("detections", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("event_id", sa.Integer(), sa.ForeignKey("network_events.id"), unique=True), sa.Column("attack_type", sa.String(64)), sa.Column("severity", sa.String(16)), sa.Column("confidence", sa.Float()), sa.Column("rule_score", sa.Float()), sa.Column("ml_score", sa.Float()), sa.Column("behavior_score", sa.Float()), sa.Column("attack_status", sa.String(32)), sa.Column("evidence", sa.Text()), sa.Column("created_at", sa.DateTime()))
    for column in ("event_id", "attack_type", "severity", "attack_status", "created_at"): op.create_index(f"ix_detections_{column}", "detections", [column])
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(255), unique=True, nullable=False), sa.Column("password_hash", sa.Text(), nullable=False), sa.Column("role", sa.String(32), nullable=False), sa.Column("active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False)); op.create_index("ix_users_email", "users", ["email"])
    op.create_table("audit_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("timestamp", sa.DateTime(), nullable=False), sa.Column("actor", sa.String(255)), sa.Column("action", sa.String(128), nullable=False), sa.Column("resource", sa.String(255)), sa.Column("details", sa.Text()), sa.Column("source_ip", sa.String(64)))
    for column in ("timestamp", "actor", "action"): op.create_index(f"ix_audit_logs_{column}", "audit_logs", [column])
    op.create_table("ingestion_jobs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_name", sa.String(255), nullable=False), sa.Column("log_format", sa.String(32)), sa.Column("status", sa.String(32)), sa.Column("records_processed", sa.Integer()), sa.Column("attacks_detected", sa.Integer()), sa.Column("errors", sa.Integer()), sa.Column("message", sa.Text()), sa.Column("created_at", sa.DateTime()), sa.Column("completed_at", sa.DateTime())); op.create_index("ix_ingestion_jobs_status", "ingestion_jobs", ["status"]); op.create_index("ix_ingestion_jobs_created_at", "ingestion_jobs", ["created_at"])
    op.create_table("analyst_feedback", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("detection_id", sa.Integer(), sa.ForeignKey("detections.id"), nullable=False), sa.Column("analyst_email", sa.String(255)), sa.Column("reviewed_label", sa.String(64), nullable=False), sa.Column("outcome_label", sa.String(32)), sa.Column("notes", sa.Text()), sa.Column("created_at", sa.DateTime())); op.create_index("ix_analyst_feedback_detection_id", "analyst_feedback", ["detection_id"]); op.create_index("ix_analyst_feedback_created_at", "analyst_feedback", ["created_at"])
    op.create_table("model_versions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("version", sa.String(64), unique=True, nullable=False), sa.Column("path", sa.Text(), nullable=False), sa.Column("status", sa.String(32)), sa.Column("metrics", sa.Text()), sa.Column("training_source", sa.String(255)), sa.Column("created_at", sa.DateTime()), sa.Column("activated_at", sa.DateTime())); op.create_index("ix_model_versions_version", "model_versions", ["version"])
def downgrade():
    for table in ("model_versions", "analyst_feedback", "ingestion_jobs", "audit_logs", "users", "detections", "network_events"): op.drop_table(table)
